name: Publish to AUR

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Update PKGBUILD version
        run: |
          TAG_NAME="${{ github.event.workflow_run.head_branch }}"
          VERSION="${TAG_NAME#v}"

          sed -i "s|pkgver=.*|pkgver=$VERSION|" PKGBUILD
          sed -i "s|pkgver=.*|pkgver=$VERSION|" PKGBUILD-bin

          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: Publish AUR package (source)
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: framr
          pkgbuild: ./PKGBUILD
          updpkgsums: true
          test: true
          test_flags: -s --noconfirm --clean --cleanbuild
          commit_username: vMohammad
          commit_email: vmohammad@vmohammad.dev
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ env.TAG_NAME }} (gh action)"
          ssh_keyscan_types: ed25519

      - name: Publish AUR package (binary)
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: framr-bin
          pkgbuild: ./PKGBUILD-bin
          updpkgsums: true
          test: true
          test_flags: -s --noconfirm --clean --cleanbuild
          commit_username: vMohammad
          commit_email: vmohammad@vmohammad.dev
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ env.TAG_NAME }} (gh action)"
          ssh_keyscan_types: ed25519
