name: Publish to AUR

on:
  push:
    tags:
      - "v*"

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Update PKGBUILD version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD-bin
        env:
          GITHUB_REF_NAME: ${{ github.event.workflow_run.head_branch }}

      - name: Publish AUR package (source)
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: framr
          pkgbuild: ./PKGBUILD
          updpkgsums: true
          test: true
          test_flags: -s --noconfirm --clean --cleanbuild
          commit_username: vMohammad
          commit_email: vmohammad@vmohammad.dev
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }} (gh action)"
          ssh_keyscan_types: ed25519

      - name: Publish AUR package (binary)
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: framr-bin
          pkgbuild: ./PKGBUILD-bin
          updpkgsums: true
          test: true
          test_flags: -s --noconfirm --clean --cleanbuild
          commit_username: vMohammad
          commit_email: vmohammad@vmohammad.dev
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }} (gh action)"
          ssh_keyscan_types: ed25519
