name: Build

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install System Dependencies
        run: pacman -Syu --noconfirm pkg-config wayland wayland-protocols libxkbcommon cairo pango libxcursor mesa dbus gstreamer gst-plugins-base-libs gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad gst-plugin-rav1e

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "archlinux"

      - name: Build Framr
        run: cargo build --release --locked

      - name: Package Binary
        run: |
          tar -czvf framr-${{ github.ref_name }}-x86_64-linux.tar.gz -C target/release framr

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: framr-arch-binary
          path: framr-${{ github.ref_name }}-x86_64-linux.tar.gz

  package:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends build-essential pkg-config curl ca-certificates git libwayland-dev libxkbcommon-dev libcairo2-dev libpango1.0-dev libdbus-1-dev libxcursor-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "debian"

      - name: Build Framr
        run: cargo build --release --locked

      - name: Generate shell completions and man pages
        run: |
          mkdir -p target/completions
          target/release/framr completions bash > target/completions/framr.bash
          target/release/framr completions zsh > target/completions/_framr
          target/release/framr completions fish > target/completions/framr.fish
          target/release/framr man target/man

      - name: Package deb and rpm
        run: |
          cargo install cargo-deb cargo-generate-rpm --locked
          cargo deb --no-build --no-strip
          cargo generate-rpm
          mv target/debian/*.deb target/generate-rpm/*.rpm .

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v7
        with:
          name: framr-packages
          path: |
            *.deb
            *.rpm
