name: "Push to Cachix"
on:
  push:
    branches:
      - main

jobs:
  push_to_cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: framr
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Flake
        run: nix build -L
      - name: Run Test Shell
        run: nix develop --command echo OK
