name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    permissions:
      contents: write
    steps:
      - name: Download Binary Artifact
        uses: actions/download-artifact@v8
        with:
          name: framr-arch-binary
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Package Artifact
        uses: actions/download-artifact@v8
        with:
          name: framr-packages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog from Commits
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            *.tar.gz
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
